Add gitlab support
Kong/insomnia-docs pull request #102
Opened 2022-06-07 21:47 UTC by wongstein

### Summary

Adds instructions to connect easily to gitlab

### Reason

This Docs change is necessary for the next GA release.

### Testing

2022-06-07 23:11 UTC, lena-larionova requested changes

2022-06-07 23:11 UTC, lena-larionova commented on docs/insomnia/git-sync.md
> +5.  You will be redirected to the Insomnia website which will say "Successfully authenticated Insomnia". You might be prompted to manually add your gitlab authentication manually to the Insomnia App.
```suggestion
5.  Return to the Insomnia app and wait for sync to finish.

6. You might be prompted to manually add your GitLab authentication to the Insomnia app. If you still see the option to manually paste in your GitLab authentication code, copy it from `app.insomnia.rest` into the Insomnia app, then click  **Sync**.
```

2022-06-07 23:11 UTC, lena-larionova commented on docs/insomnia/git-sync.md
> +6. You can now clone any repository from GitLab! Copy the HTTPS URI for the GitLab repository you want to connect to and paste it into the "GitLab URI" field.
```suggestion
7. You can now clone any repository from GitLab! Copy the HTTPS URI for the GitLab repository you want to connect to and paste it into the "GitLab URI" field.
```

2022-06-08 20:18 UTC, wongstein commented on docs/insomnia/git-sync.md
> +1. Click on the **Setup Git Sync** on the upper right hand corner of the Insomnia App.
Ah yes it probably is a holdover from Insomnia Designer.  Good catch!

2022-06-09 15:57 UTC, merged