domain capture
Kong/insomnia-docs pull request #240
Opened 2024-11-19 20:04 UTC by Guaris

Docs on domain capture added to the manage domains doc.

2024-11-20 14:54 UTC, cloudjumpercat requested changes
@Guaris Left a few suggestions!

2024-11-20 14:54 UTC, cloudjumpercat commented on docs/insomnia/manage-domains.md
> +2. Toggle the **Enable** button. You will see a pop-up modal asking you to enable capture.
```suggestion
2. Click the **Enable** toggle. You will see a pop-up modal asking you to enable capture. 
```
https://developers.google.com/style/ui-elements#term-toggle

2024-11-20 14:54 UTC, cloudjumpercat commented on docs/insomnia/manage-domains.md
> +
```suggestion
## Domain Capture

Domain capture allows you to consolidate all user accounts in your Insomnia org into one Enterprise team.

```

2024-11-20 14:54 UTC, cloudjumpercat commented on docs/insomnia/manage-domains.md
> +Once domain capture is enabled, you can see all captured accounts from the [**Licenses** tab](https://app.insomnia.rest/app/enterprise/licenses). All new users with this domain will be captured autom
```suggestion
Once domain capture is enabled, you can see all captured accounts in the [**Licenses** tab](https://app.insomnia.rest/app/enterprise/licenses). All new users with this domain will be captured automatically. From the license page, the owner or co-owner of the organization can delete any deactivated accounts. These accounts can still log in, but they won't have access to enterprise data.
```

2024-11-21 07:04 UTC, notjaywu reviewed
@Guaris left one comment

2024-11-21 07:04 UTC, notjaywu commented on docs/insomnia/manage-domains.md
> +1. Navigate to the [domain settings](https://app.insomnia.rest/app/domains/list).
```suggestion
1. Navigate to the [domain settings](https://app.insomnia.rest/app/enterprise/domains/list). 
```

2024-11-29 02:19 UTC, notjaywu approved these changes

2024-12-11 14:08 UTC, cloudjumpercat approved these changes
LGTM!

2024-12-13 20:03 UTC, merged